version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - sudo chmod +x gradlew
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'slackmoviemaster-1.0.jar'
  discard-paths: yes
  base-directory: 'build/libs'