version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - gradle build
  post_build:
    commands:
      - echo Build completed on `date`
      - cd target && ls -la
artifacts:
  files:
    - 'slackmoviemaster-1.0.jar'
  discard-paths: yes
  base-directory: 'target'